### PR TITLE
fix(core): pass req.params to next handler

### LINKED ISSUE #314: Subapps not receiving params from parent apps
**Describe the bug**

A parent app that does ` app.use("/:path", subapp)`  doesn't pass req.params.path to the subapp.

**To Reproduce**

Code to reproduce the behavior:
```js
import { App } from "@tinyhttp/app";
const subapp = new App().get("/", (req, res) => {
  if (req.params.test == null) {
    res.send("req.params.test not passed");
  } else {
    res.send(`req.params.test passed: ${req.params.test}`);
  }
});
new App()
  .use("/:test", subapp)
  .listen(8080, () => console.log("listening on http://localhost:8080"));
```

**Expected behavior**

`req.params.test` is passed to the subapp

**Versions**

- `node`: 16.3.0
- `@tinyhttp/app`: 2.0.3

### PR DESCRIPTION
**Pull request by tbhmens**
Also modified tests to check req.params
Closes #314

### CODE REVIEW

**Comment by talentlessguy** [comment]
LGTM, could you also run `pnpm chgset` for the package you fixed bug in?

**Comment by tbhmens** [comment]
👍 done

**Comment by talentlessguy** [comment]
I think you forgot to run `pnpm chgset` to bump a package's version

**Comment by tbhmens** [comment]
not sure how chgset works, i think i did right? it made a clever-camels-relate file 🤷

**Comment by talentlessguy** [comment]
@tbhmens you should select a patch version update in `pnpm chgset` for `@/app`

**Comment by tbhmens** [comment]
pretty sure i did that, 692225659e27e7ebb0a7e54aadbe38ce48043d6d

**Comment by talentlessguy** [comment]
package.json file hasn't changed

**Comment by tbhmens** [comment]
ohh, the chgset command might've ran wrong or something. 👍 fixed

**Comment by talentlessguy** [comment]
thanks! and sorry for inconvenience, changesets is sometimes buggy

**Comment by talentlessguy** [comment]
@all-contributors add @tbhmens for bug, code

**Pull request merged**
