### PR TITLE
CLI: use the project name as name in package.json

### PR DESCRIPTION
**Pull request by paolotiu**
Adds: #263
Hey @talentlessguy, does this look good? 
I can make changes if needed, thank you :)

### CODE REVIEW

**Comment by talentlessguy** [comment]
could you please change commit message to follow CommitLint

**Comment by paolotiu** [comment]
> could you please change commit message to follow CommitLint
Got it! Sorry for that.

**Comment by talentlessguy** [comment]
tests seem to pass, thanks for the fix

**Comment by talentlessguy** [comment]
@all-contributors add @paolotiu for bug

**Comment by talentlessguy** [comment]
ummm... why does all contributors not work :thinking:

**Comment by talentlessguy** [comment]
@all-contributors add @paolotiu for code

**Pull request merged**
